# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       patchutils

# >> macros
# << macros

Summary:    A collection of programs for manipulating patch files.
Version:    0.3.3
Release:    1
Group:      Applications/System
License:    GPL
URL:        http://cyberelk.net/tim/patchutils/
Source0:    %{name}-%{version}.tar.bz2
Source100:  patchutils.yaml

%description
This is a collection of programs that can manipulate patch files in
useful ways such as interpolating between two pre-patches, combining
two incremental patches, fixing line numbers in hand-edited patches,
and simply listing the files modified by a patch.


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
./bootstrap
./configure --prefix=/usr/
# << build pre


make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post

%files
%defattr(-,root,root,-)
%{_bindir}
# >> files
# << files
